{{- $envVars := include "grist.common.env" (list . .Values.docWorker) -}}
{{- $fullName := include "grist.doc.fullname" . -}}
{{- $component := "doc-worker" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "grist.common.labels" (list . $component) | nindent 4 }}
spec:
  replicas: {{ .Values.docWorker.replicas }}
  selector:
    matchLabels:
      {{- include "grist.common.selectorLabels" (list . $component) | nindent 6 }}
  template:
    metadata:
      annotations:
        fileChecksum: {{ include (print $.Template.BasePath "/file_cm.yaml") . | sha256sum }}
        {{- with .Values.docWorker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "grist.common.selectorLabels" (list . $component) | nindent 8 }}
    spec:
      {{- if $.Values.image.credentials }}
      imagePullSecrets:
        - name: {{ include "grist.secret.dockerconfigjson.name" (dict "fullname" (include "grist.fullname" .) "imageCredentials" $.Values.image.credentials) }}
      {{- end}}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ (.Values.docWorker.image | default dict).repository | default .Values.image.repository }}:{{ (.Values.docWorker.image | default dict).tag | default .Values.image.tag }}"
          imagePullPolicy: {{ (.Values.docWorker.image | default dict).pullPolicy | default .Values.image.pullPolicy }}
          {{- with .Values.docWorker.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.docWorker.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: APP_DOC_URL
              value: https://{{ .Values.ingress.host }}/dw/$(POD_IP)
            - name: GRIST_DOC_WORKER_ID
              value: $(POD_IP)
            - name: APP_DOC_INTERNAL_URL
              value: http://{{ include "grist.lb.fullname" . }}/internal/$(POD_IP)
            {{- if $envVars}}
            {{- $envVars | indent 12 }}
            {{- end }}
          {{- with .Values.docWorker.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.docWorker.service.targetPort }}
              protocol: TCP
          {{- if .Values.docWorker.probes.liveness }}
          livenessProbe:
            {{- include "grist.probes.abstract" (merge .Values.docWorker.probes.liveness (dict "targetPort" .Values.docWorker.service.targetPort )) | nindent 12 }}
          {{- end }}
          {{- if .Values.docWorker.probes.readiness }}
          readinessProbe:
            {{- include "grist.probes.abstract" (merge .Values.docWorker.probes.readiness (dict "targetPort" .Values.docWorker.service.targetPort )) | nindent 12 }}
          {{- end }}
          {{- if .Values.docWorker.probes.startup }}
          startupProbe:
            {{- include "grist.probes.abstract" (merge .Values.docWorker.probes.startup (dict "targetPort" .Values.docWorker.service.targetPort )) | nindent 12 }}
          {{- end }}
          {{- with .Values.docWorker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- range $index, $value := .Values.mountFiles }}
            - name: "files-{{ $index }}"
              mountPath: {{ $value.path }}
              subPath: content
            {{- end }}
            {{- range $name, $volume := .Values.docWorker.persistence }}
            - name: "{{ $name }}"
              mountPath: "{{ $volume.mountPath }}"
            {{- end }}
      {{- with .Values.docWorker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.docWorker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.docWorker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- range $index, $value := .Values.mountFiles }}
        - name: "files-{{ $index }}"
          configMap:
            name: "{{ include "grist.fullname" $ }}-files-{{ $index }}"
        {{- end }}
        {{- range $name, $volume := .Values.docWorker.persistence }}
        - name: "{{ $name }}"
          {{- if eq $volume.type "emptyDir" }}
          emptyDir: {}
          {{- else }}
          persistentVolumeClaim:
            claimName: "{{ $fullName }}-{{ $name }}"
          {{- end }}
        {{- end }}
